name: From The Bunker
favicon: null
layout_spectrum: 0.26786769297905266
typography_spectrum: 0.597502235788852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9802835278678685
  lightness: 0.6473428118042648
  saturation: 0.09644325054250658
  rhythmicContrast: 0.3472533328458667
purpose: []
